"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Mage_1 = require("./Mage");
const Warrior_1 = require("./Warrior");
const Priest_1 = require("./Priest");
let mage = new Mage_1.Mage("Mago");
let warrior = new Warrior_1.Warrior("Warrior");
let priest = new Priest_1.Priest("Priest");
console.log(mage);
console.log(warrior);
console.log(priest);
